version: "3.9"
services:
  search_server:
    image: pqai_api
    stdin_open: true
    tty: true
    restart: always
    network_mode: host
    volumes:
      - ${MODELS_DIR}:/app/models
      - ${INDEXES_DIR}:/app/indexes
      - ${TOKENS_FILE}:/app/tokens.txt
    environment:
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      API_PORT: ${API_PORT}
      PQAI_S3_BUCKET_NAME: ${PQAI_S3_BUCKET_NAME}
      SENTRY_URL: ${SENTRY_URL}